name = "task-queue-calendar"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
ALLOWED_ORIGIN = "https://hkao-task-queue.web.app,http://localhost:5173,http://localhost:5174"
FIREBASE_PROJECT_ID = "hkao-task-queue"

[[kv_namespaces]]
binding = "CALENDAR_KV"
id = "589dc9d1e4b64e1f93d029dc7a63b0a8"
